name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - name: Use Node.js 21
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 22
        cache: 'npm'
    - run: npm install      
    - run: npm test

  sonarcloud:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0  
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22 
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}